name: Dry Run Nginx Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dry-run:
    uses: ./.github/workflows/template-release.yaml
    with:
      target: nginx
      tag: dryrun-nginx-${{ github.run_id }}
      release_files: |-
        nginx/sbin/nginx
      upload_release: false
    secrets: inherit
