name: Release Haproxy From Tag

on:
  push:
    tags:
      - 'haproxy-*'

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/template-release.yaml
    with:
      target: haproxy
      tag: ${{ github.ref_name }}
      release_asset: haproxy/output/sbin/haproxy
      upload_release: true
      no_cache: false
    secrets: inherit
