name: Release Httpd From Tag

on:
  push:
    tags:
      - 'httpd-*'

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/template-release.yaml
    with:
      target: apache-httpd
      tag: ${{ github.ref_name }}
      release_files: |
        apache-httpd/output/bin/httpd
      upload_release: true
      no_cache: false
    secrets: inherit
