name: Release Vector From Tag

on:
  push:
    tags:
      - 'vector-*'

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/template-release.yaml
    with:
      target: vector
      tag: ${{ github.ref_name }}
      release_files: |-
        vector/bin/vector
      upload_release: true
    secrets: inherit
