name: Release Dnsmasq From Tag

on:
  push:
    tags:
      - 'dnsmasq-*'

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/template-release.yaml
    with:
      target: dnsmasq
      tag: ${{ github.ref_name }}
      release_asset: dnsmasq/output/sbin/dnsmasq
      upload_release: true
      no_cache: false
    secrets: inherit
