name: Release Monit From Tag

on:
  push:
    tags:
      - 'monit-*'

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/template-release.yaml
    with:
      target: monit
      tag: ${{ github.ref_name }}
      release_files: |-
        monit/bin/monit
      upload_release: true
    secrets: inherit
