name: Release Coredns From Tag

on:
  push:
    tags:
      - 'coredns-*'

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/template-release.yaml
    with:
      target: coredns
      tag: ${{ github.ref_name }}
      release_files: |
        coredns/output/coredns
      upload_release: true
      no_cache: false
    secrets: inherit
