name: Release Haproxy From Tag

on:
  push:
    tags:
      - 'haproxy-*'

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/template-release.yaml
    with:
      target: haproxy
      tag: ${{ github.ref_name }}
      release_files: |-
        haproxy/sbin/haproxy
      upload_release: true
    secrets: inherit
